# Introduction 

Things to learn in Javascript: 

- How to include Javascript for use in the HTML
  - Internal Javascript
  - External Javascript
  
- How to display Javascript output
  - using innerHTML
  - document.write()
  - window.alert()
  - console.log()
  
- How to declare variables
  - var
  - const
  - let

- Global scope and local scope
  - https://www.digitalocean.com/community/tutorials/understanding-variables-scope-hoisting-in-javascript

How to make variable usable outside of scope.

// Use var to initialize a variable
var species = "human";

if (fullMoon) {
  // Attempt to create a new variable in a block
  var species = "werewolf";
  console.log(`It is a full moon. Lupin is currently a ${species}.`);
}

console.log(`It is not a full moon. Lupin is currently a ${species}.`);

How to save data in CSV
https://www.javatpoint.com/javascript-create-and-download-csv-file


How to create an object
var object = { 
  age : 12,
  happy: true, 
  alerting : function(){
  alert("hello), 
  
}; 

Accessing object by object.age or object.alerting().
Add to object by object.somethingNew = "new ideas";
Delete something unwanted in the object using delete object.age

https://bhansa.github.io/blog/Creating-a-Covid-tracker-with-Vanilla-JS/


Data frame in javascript
https://danfo.jsdata.org/getting-started

https://js4ds.org/ 

Eloquent JavaScript: A Modern Introduction to Programming
Haverbeke, Marijn
https://ebookcentral.proquest.com/lib/nielib-ebooks/reader.action?docID=1931623&ppg=229 

Data visualization with JavaScript / Stephen A. Thomas.
Thomas, Stephen A., 1962- author.
https://ebookcentral.proquest.com/lib/nielib-ebooks/reader.action?docID=4503149

Vue JS
https://ebookcentral.proquest.com/lib/nielib-ebooks/reader.action?docID=5322215&ppg=19

https://freshman.tech/random-quote-machine/


## Create PDF

https://pdf-lib.js.org/#install 
https://jsfiddle.net/Hopding/rxwsc8f5/13/

## how to use persistent data


Plan -
Make a seperate page to create the download PDF. 
- see if can port the data over. may not be possible.  
- use same page. persistent data

Graph-based data
- https://gun.eco/
- https://graphql.org/
- https://neo4j.com/
- https://www.g2.com/categories/graph-databases/free
- https://uhack-guide.readthedocs.io/en/latest/technical/graph-dbs/
